# This is a basic workflow to help you get started with Actions

name: generate-datasets

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: push
  # schedule:
  #   - cron:  '* * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  generate:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - uses: goanpeca/setup-miniconda@v1
      with:
        miniconda-version: 'latest'
        environment-file: environment.yml
        activate-environment: covid

    # Runs a single command using the runners shell
    - name: install
      shell: bash -l {0}
      run: |
        conda info
        conda list
        python --version
        which python
        yarn install
        make fix

    # Runs a set of commands using the runners shell
    - name: generate datasets
      shell: bash -l {0}
      run: |
        conda info
        conda list
        python --version
        which python
        make generate
        ls -lH datasets
        git status
